;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        MikeDeIndent
        MikeIndent
        autopair-insert-opening
        autopair-insert-or-skip-quote
        autopair-newline
        clipboard-kill-region
        clipboard-kill-ring-save
        clipboard-yank
        indent-for-tab-command
        mark-paragraph
        python-indent-electric-colon
        query-replace
        sh-assignment
        ))

(setq mc/cmds-to-run-once
      '(
        company-complete
        ))
