;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        MikeDeIndent
        MikeGetIndentation
        MikeIndent
        autopair-insert-opening
        autopair-insert-or-skip-paired-delimiter
        autopair-insert-or-skip-quote
        autopair-newline
        autopair-skip-close-maybe
        backward-sexp
        c-electric-colon
        c-electric-delete-forward
        c-electric-semi&comma
        c-electric-slash
        calc-dispatch
        clipboard-kill-region
        clipboard-kill-ring-save
        clipboard-yank
        comment-dwim
        delete-indentation
        duplicate-current-line-or-region
        electric-newline-and-maybe-indent
        eval-print-last-sexp
        expand-abbrev
        forward-sentence
        forward-sexp
        git-rebase-squash
        helm-ag--mark-line-deleted
        helm-confirm-and-exit-minibuffer
        indent-for-tab-command
        indent-new-comment-line
        indent-region
        indent-rigidly
        indent-rigidly-left-to-tab-stop
        indent-rigidly-right-to-tab-stop
        isearch-backward-regexp
        isearch-printing-char
        mark-paragraph
        markdown-exdent-or-delete
        sgml-close-tag
        sh-assignment
        split-line
        toggle-comment-region-or-line
        xterm-paste
        yaml-electric-backspace
        yaml-electric-bar-and-angle
        yaml-electric-dash-and-dot
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        MikeDownSomeLines
        MikeUpSomeLines
        describe-key
        helm-M-x
        isearch-forward-regexp
        shell-command
        toggle-meta-lock
        yank-rectangle
        ))
