;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        MikeDeIndent
        MikeIndent
        backward-sexp
        clipboard-kill-region
        clipboard-kill-ring-save
        clipboard-yank
        duplicate-current-line-or-region
        forward-sexp
        helm-confirm-and-exit-minibuffer
        indent-for-tab-command
        ))

(setq mc/cmds-to-run-once
      '(
        ))
