;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        MikeDeIndent
        MikeIndent
        autopair-insert-opening
        autopair-insert-or-skip-paired-delimiter
        autopair-insert-or-skip-quote
        autopair-newline
        backward-sexp
        clipboard-kill-region
        clipboard-kill-ring-save
        clipboard-yank
        duplicate-current-line-or-region
        forward-sentence
        forward-sexp
        helm-confirm-and-exit-minibuffer
        indent-for-tab-command
        markdown-exdent-or-delete
        split-line
        yaml-electric-dash-and-dot
        ))

(setq mc/cmds-to-run-once
      '(
        MikeDownSomeLines
        MikeUpSomeLines
        yaml-electric-backspace
        ))
